apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  # push:
  #   branches:
  #     - '**'
  workflow_dispatch:
    inputs:
      workflowinput1:
        type: string
        required: true
jobs:
  test:
    steps:
      - name: Say hello 1
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "sleep"
          sleep 10
          echo "Hello 1"
